export const HOMESLIDER_FETCH_START = "home/HOMESLIDER_FETCH_START";
export const HOMESLIDER_FETCH_COMPLETED = "home/HOMESLIDER_FETCH_COMPLETED";
export const HOMESLIDER_FETCH_REJECTED = "home/HOMESLIDER_FETCH_REJECTED";
